### ISSUE TITLE
OTA updates fail

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/l4m_website#18]
Until some time the updates via the integrated downloader do not seem to work. 

First, after the reboot the ZIP file does not end with ".zip", but ".zip.decrypt" (or similar). What is causing this?

Also when renaming it and trying to apply it, the ZIP is not valid…

14.1
Device: jfltexx

**Comment by rugk** [comment]
Do you know what that `.unencrypt` means? Maybe it prepares that for automated installation – which does not run, but that would not be too bad, as manual installation would still be fine.

**Comment by rugk** [comment]
Also this exception now happens, when I tap the downloaded update file in the updater app (probably, because I renamed the file and it is "not there" anymore):
``` 
03-26 21:03:00.230 12622 12622 E UpdateListAdapter: Could not determine the type of the update
03-26 21:03:00.243 12622 12622 D AndroidRuntime: Shutting down VM
03-26 21:03:00.244 12622 12622 E AndroidRuntime: FATAL EXCEPTION: main
03-26 21:03:00.244 12622 12622 E AndroidRuntime: Process: org.lineageos.updater, PID: 12622
03-26 21:03:00.244 12622 12622 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.AlertDialog android.support.v7.app.AlertDialog$Builder.show()' on a null object reference
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at org.lineageos.updater.UpdatesListAdapter$5.onClick(UpdatesListAdapter.java:371)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at org.lineageos.updater.UpdatesListAdapter$9.onClick(UpdatesListAdapter.java:428)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
03-26 21:03:00.244 12622 12622 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
03-26 21:03:00.247  2488  2994 W ActivityManager:   Force finishing activity org.lineageos.updater/.UpdatesActivity
[…later]
03-26 21:03:47.587  2488  2994 I ActivityManager: Killing 12622:org.lineageos.updater/u0a5 (adj 0): crash
```

**Comment by corna** [comment]
This was probably caused by the updater changes in LineageOS; it should be fixed now, am I correct?

**Comment by rugk** [comment]
I'll try it later…

**Comment by rugk** [comment]
works again
